require("prototypes.entity")
require("prototypes.items")
require("prototypes.recipe-category")
require("prototypes.recipe")
require("prototypes.recipe-advanced-air-purification")
require("prototypes.technology")
